name: unify
description: "Unify is a mobile application that aims to provide authentic teammates for competitive mobile Esports"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


# -------------------- PACKAGES -------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  cupertino_icons: ^1.0.2 # IOS icons
  go_router: ^13.2.0
  provider: ^6.1.1
  http: ^0.13.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  flutter_secure_storage: ^4.2.1
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  amazon_cognito_identity_dart_2: ^3.6.2
  image_picker: ^0.8.4+4
  shared_aws_api: ^2.0.0
  simple_s3: 0.3.2
  amplify_auth_cognito: ^1.0.0
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  file_picker: ^6.2.0

# -------------------- ./ PACKAGES END -------------------- #


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  # -------------------- LOCAL ASSETS -------------------- #
  assets:
    - assets/images/brawlstars/brawler_icons/
    - assets/images/brawlstars/misc/
    - assets/images/brawlstars/rank_plates/
    - assets/images/game_banner/
    - assets/images/logos/
    - assets/images/avatars/
    - .env

  # -------------------- LOCAL FONTS -------------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
    - family: Righteous
      fonts:        
        - asset: assets/fonts/Righteous-Regular.ttf
    - family: Roboto_Slab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf