name: unify
description: "Unify is a mobile application that aims to provide authentic teammates for competitive mobile Esports"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


# -------------------- PACKAGES -------------------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  cupertino_icons: ^1.0.2 # IOS icons
  go_router: ^13.2.0
  provider: ^6.1.1
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1

# -------------------- ./ PACKAGES END -------------------- #


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  # -------------------- LOCAL ASSETS -------------------- #
  assets:
    - assets/images/brawlstars/brawler_icons/
    - assets/images/brawlstars/misc/
    - assets/images/brawlstars/rank_plates/
    - assets/images/game_banner/
    - assets/images/logos/
    - .env

  # -------------------- LOCAL FONTS -------------------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
    - family: Righteous
      fonts:        
        - asset: assets/fonts/Righteous-Regular.ttf
    - family: Roboto_Slab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf