Map<String, String> brawlerToImageStrMap = Map.fromEntries({
  "8-BIT": "8-Bit.webp",
  "AMBER": "Amber.webp",
  "ASH": "Ash.webp",
  "BARLEY": "Barley.webp",
  "BEA": "Bea.webp",
  "BELLE": "Belle.webp",
  "BIBI": "Bibi.webp",
  "BO": "Bo.webp",
  "BONNIE": "Bonnie.webp",
  "BROCK": "Brock.webp",
  "BULL": "Bull.webp",
  "BUSTER": "Buster.webp",
  "BUZZ": "Buzz.webp",
  "BYRON": "Byron.webp",
  "CARL": "Carl.webp",
  "CHARLIE": "Charlie.webp",
  "CHESTER": "Chester.webp",
  "CHUCK": "Chuck.png",
  "COLETTE": "Colette.webp",
  "COLT": "Colt.webp",
  "CORDELIUS": "Cordelius.webp",
  "CROW": "Crow.png",
  "DARRYL": "Darryl.webp",
  "DOUG": "Doug.webp",
  "DYNAMIKE": "Dynamike.webp",
  "EDGAR": "Edgar.png",
  "EL PRIMO": "El-Primo.png",
  "EMZ": "Emz.webp",
  "EVE": "Eve.webp",
  "FANG": "Fang.png",
  "FRANK": "Frank.webp",
  "GALE": "Gale.webp",
  "GENE": "Gene.webp",
  "GRAY": "Gray.webp",
  "GRIFF": "Griff.webp",
  "GROM": "Grom.webp",
  "GUS": "Gus.webp",
  "HANK": "Hank.webp",
  "JACKY": "Jacky.webp",
  "JANET": "Janet.webp",
  "JESSIE": "Jessie.webp",
  "KIT": "Kit.png",
  "LARRY & LAWRIE": "Larry-&-Lawrie.webp",
  "LEON": "Leon.webp",
  "LOLA": "Lola.webp",
  "LOU": "Lou.webp",
  "MAISIE": "Maisie.webp",
  "MAX": "Max.webp",
  "MEG": "Meg.webp",
  "MICO": "Mico.webp",
  "MORTIS": "Mortis.webp",
  "MR. P": "Mr-P.webp",
  "NANI": "Nani.webp",
  "NITA": "Nita.webp",
  "OTIS": "Otis.webp",
  "PAM": "Pam.webp",
  "PEARL": "Pearl.webp",
  "PENNY": "Penny.webp",
  "PIPER": "Piper.webp",
  "POCO": "Poco.webp",
  "R-T": "R-T.webp",
  "RICO": "Rico.webp",
  "ROSA": "Rosa.webp",
  "RUFFS": "Ruffs.webp",
  "SAM": "Sam.webp",
  "SANDY": "Sandy.webp",
  "SHELLY": "Shelly.webp",
  "SPIKE": "Spike.webp",
  "SPROUT": "Sprout.webp",
  "SQUEAK": "Squeak.webp",
  "STU": "Stu.webp",
  "SURGE": "Surge.webp",
  "TARA": "Tara.webp",
  "TICK": "Tick.webp",
  "WILLOW": "Willow.webp",
}.entries);

String brawlerBackendToAssetImageStr(String brawler) {
  return brawlerToImageStrMap[brawler] ?? "Shelly.webp";
}
